# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw3_config = debug
  rf_config = debug
endif
ifeq ($(config),release)
  glfw3_config = release
  rf_config = release
endif

PROJECTS := glfw3 rf

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glfw3:
ifneq (,$(glfw3_config))
	@echo "==== Building glfw3 ($(glfw3_config)) ===="
	@${MAKE} --no-print-directory -C . -f glfw3.make config=$(glfw3_config)
endif

rf: glfw3
ifneq (,$(rf_config))
	@echo "==== Building rf ($(rf_config)) ===="
	@${MAKE} --no-print-directory -C . -f rf.make config=$(rf_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f glfw3.make clean
	@${MAKE} --no-print-directory -C . -f rf.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw3"
	@echo "   rf"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"